# Generated by Django 6.0.3 on 2026-05-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_currency_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
